- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    apt: 
      name: htop
      state: latest

  - name: ensure that my default packages is installed
    apt:
      pkg:
      - joe
      - cloc
      - openjdk-11-jdk
      - openjdk-11-source
      - curl
      - docker
      - docker-compose
      - git
      - meld
      - openvpn
      - slack
      - teams
      - spotify  