- hosts: localhost
  become: true
  
#  vars:
#    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  
  pre_tasks:
    - name: update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: false
      
       
  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
  
#TODO  - name: openvpn setup to home 
#TODO  - name: ensure eclipse is installed 
#TODO  - name: eclipse setup
#TODO  - name: ensure vlc is installed 
#TODO  - name: ensure maven completion is installed  
#TODO  - name: ssh keys 
#TODO  - name: get github projects
#TODO  - name: copy maven thuis-settings.xml
#TODO    copy: 
#TODO      src: ./maven_settings/thuis-settings.xml 
#TODO      dest: {{home_dir}}/.m2/thuis-settings.xml
#TODO  - name: symlink maven settings
#TODO    file:
#TODO      src: "{{home_dir}}/.m2/thuis-settings.xml"
#TODO      dest: "{{home_dir}}/.m2/settings.xml"
#TODO      state: link  
#TODO - name: Remove useless packages that are no longer required
#  apt:
#    autoremove: yes
#    autoclean: yes