- hosts: localhost
  become: true
  
  pre_tasks:
    - name: update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: false
      
       
  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml 
      vars: 
        chrome_apt_file: "/etc/apt/sources.list.d/google-chrome.list"
        spotify_apt_file: "/etc/apt/sources.list.d/spotify.list"
    - include: tasks/gnome.yml
  
#TODO  - name: openvpn setup to home 
#TODO  - name: ensure eclipse is installed 
#TODO  - name: eclipse setup
#TODO  - name: ensure vlc is installed 
#TODO  - name: ssh keys 
#TODO  - name: get github projects
#TODO - name: Remove useless packages that are no longer required
  post_tasks:
  - name: remove all unused packages
    apt:
      autoremove: yes
