- hosts: localhost
  become: true
  
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  
  pre_tasks:
  - name: update all packages to the latest version
    apt:
      upgrade: dist
      update_cache: yes
      changed_when: false
       
  tasks:
  - include: tasks/packages.yml