- hosts: localhost
  become: true
  tasks:
    - name: ensure that my default packages is installed
      apt:
        pkg:
        - joe
        - cloc
        - openjdk-11-jdk
        - openjdk-11-source
        - curl
        - docker
        - docker-compose
        - git
        - meld
        - openvpn
        - teams
        - maven
        
    - name: Install slack from url
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.8.0-amd64.deb
        
        