- hosts: localhost
  become: true
  tasks:
    - name: ensure that my default packages is installed
      apt:
        pkg:
        - joe
        - cloc
        - openjdk-11-jdk
        - openjdk-11-source
        - curl
        - docker
        - docker-compose
        - git
        - meld
        - openvpn