- name: Install python-psutil package
  apt: name=python-psutil

- name: Copy wallpaper file
  copy: 
    src: files/wallpaper.jpg 
    dest: /home/bob/.wallpaper.jpg 
    owner: bob 
    group: bob 
    mode: 600

- name: Set GNOME Wallpaper
  become_user: bob
  dconf: 
    key: "/org/gnome/desktop/background/picture-uri" 
    value: "'file:///home/bob/.wallpaper.jpg'"

- name: adding favorite apps
  become_user: bob
  dconf:
    key: "org/gnome/shell/favorite-apps"
    value: "['org.gnome.Terminal.desktop', 'google-chrome.desktop', 'eclipse.desktop', 'slack.desktop', 'spotify.desktop', 'org.gnome.Nautilus.desktop', 'teams.desktop']"
    