- name: Install python-psutil package
  apt: 
    name: python-psutil

- name: Copy wallpaper file
  copy: 
    src: files/wallpaper.jpg 
    dest: /home/bob/.wallpaper.jpg 
    owner: bob 
    group: bob 
    mode: 600

- name: Set GNOME Wallpaper
  become_user: bob
  dconf: 
    key: "/org/gnome/desktop/background/picture-uri" 
    value: "'file:///home/bob/.wallpaper.jpg'"
    
#TODO
#TODO- name: adding favorite apps
#TODO  become_user: bob
#TODO  dconf:
#TODO    key: "org/gnome/shell/favorite-apps"
#TODO   value: "['org.gnome.Terminal.desktop', 'google-chrome.desktop', 'eclipse.desktop', 'slack.desktop', 'spotify.desktop', 'org.gnome.Nautilus.desktop', 'teams.desktop']"
    
