- name: ensure that my default packages are installed
  apt:
    pkg:
    - joe
    - cloc
    - openjdk-11-jdk
    - openjdk-11-source
    - curl
    - docker
    - docker-compose
    - git
    - meld
    - openvpn
    #- teams
    - maven
    - network-manager-openvpn
    - pptp-linux
    
- name: Install slack from url
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.8.0-amd64.deb
    
#Chrome browser    
- name: Does the Google apt file exist?
  ansible.builtin.shell: test -f {{chrome_apt_file}}
  register: google_apt_exists
  ignore_errors: True
  changed_when: false

- name: Add Google Chrome key
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
  copy: 
    content: "deb http://dl.google.com/linux/chrome/deb/ stable main" 
    dest: "{{chrome_apt_file}}" 
    owner: root 
    group: root 
    mode: "644"
  when: google_apt_exists.rc == 1

- name: Update apt cache
  apt: 
    update_cache: yes
  when: google_apt_exists.rc == 1

- name: Install Google Chrome
  apt: 
    pkg: google-chrome-stable
  
  # Spotify
- name: Does the Spotify apt file exist?
  ansible.builtin.shell: test -f {{spotify_apt_file}}
  register: spotify_apt_exists
  ignore_errors: True
  changed_when: false

- name: Add Spotify key
  shell: wget -q -O - https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add -
  when: spotify_apt_exists.rc == 1

- name: Add Spotify repo
  copy: 
    content: "deb http://repository.spotify.com stable non-free" 
    dest: "{{spotify_apt_file}}" 
    owner: root 
    group: root 
    mode: "644"
  when: spotify_apt_exists.rc == 1

- name: Update apt cache
  apt: 
    update_cache: yes
  when: spotify_apt_exists.rc == 1

- name: Install Spofify
  apt: 
    pkg: spotify-client

#terraform
- name: Does the Terraform apt file exist?
  ansible.builtin.shell: test -f {{terraform_apt_file}}
  register: terraform_apt_exists
  ignore_errors: True
  changed_when: false

- name: Add Terraform key
  shell: wget -q -O - https://apt.releases.hashicorp.com/gpg | apt-key add -
  when: google_apt_exists.rc == 1

- name: Set ubuntu release 
  ansible.builtin.shell: lsb_release -cs
  register: ubuntu_release
  
- name: show ubuntu release set
  ansible.builtin.debug:
    var: ubuntu_release
    
- name: Add Terraform repo
  copy: 
    content: "deb [arch-amd64] https://apt.releases.hashicorp.com {{ ubuntu_release }} main" 
    dest: "{{terraform_apt_file}}" 
    owner: root 
    group: root 
    mode: "644"
  when: terraform_apt_exists.rc == 1

- name: Update apt cache
  apt: 
    update_cache: yes
  when: terraform_apt_exists.rc == 1

- name: Install Terraform
  apt: 
    pkg: terraform
  
